apiVersion: v1
kind: Pod
metadata:
  name: ros2-publisher
spec:
  hostNetwork: true
  containers:
  - name: publisher
    image: osrf/ros:humble-desktop
    command: ["/bin/bash", "-c"]
    args:
      - "source /opt/ros/humble/setup.bash && /opt/ros/humble/lib/examples_rclcpp_minimal_publisher/publisher_lambda; sleep infinity"
    env:
      - name: ROS_DOMAIN_ID
        value: "0"

